import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      'allsaints.hk',
      'assets.ajio.com',
      'bta.scene7.com',
      'cdn-jnbkl.nitrocdn.com',
      'cdn.culture-circle.com',
      'cdn.deloox.com',
      'cdn.findyourkicks.com',
      'cdn.shopify.com',
      'cdna.lystit.com',
      'crepdogcrew.com',
      'culture-cirlce-static-dge7g8b8eue6fvcv.z02.azurefd.net',
      'encrypted-tbn0.gstatic.com',
      'freesociety.in',
      'hrd-live.cdn.scayle.cloud',
      'houseofplutus.mos.ap-southeast-2.sufybkt.com',
      'hustleculture.co.in',
      'hypefly.co.in',
      'i.ebayimg.com',
      'i.pinimg.com',
      'image-cdn.hypb.st',
      'image.goat.com',
      'images-cdn.ubuy.co.in',
      'images.stockx.com',
      'img.stadiumgoods.com',
      'img.tatacliq.com',
      'javisneaker.com',
      'luxurysouq.com',
      'media-assets.grailed.com',
      'media.endclothing.com',
      'odto.com',
      'ofour.com',
      'res.cloudinary.com',
      'sneakerplug.co.in',
      'stayfresh.ca',
      'uk.bape.com',
      'unmatchedkicks.in',
      'www.allsaints.com',
      'www.crepslocker.com',
      'www.culture-circle.com',
      'www.curatedsupply.com',
      'www.fridaycharm.com',
      'www.kicksmachine.com',
      'www.oakshop.ca',
      'www.outlined.ca',
      'www.thebckspace.com',
    ],
  },
};

export default nextConfig;
